services:
  angular-app:
    container_name: angular-container
    build:
      context: ./frontend/stream-client
      target: development
    develop:
      watch:
        - action: sync
          path: ./frontend/stream-client/src
          target: /app/src
          initial_sync: true
          ignore:
            - node_modules/
    ports:
      - 4200:4200

  nestjs-app:
    container_name: nestjs-container
    depends_on:
      - mysql-db
    build:
      context: /backend
      target: development
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - ANGULAR_URL=$ANGULAR_APP_URL
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /app/src
          initial_sync: true
          ignore:
            - node_modules/

  mysql-db:
    container_name: mysql-container
    image: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-volume:/var/lib/mysql:rw

volumes:
  mysql-volume:
