FROM node:20-alpine AS base
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

FROM base AS development 
COPY . .
CMD ["npx", "ng", "serve", "--host", "0.0.0.0"]

FROM base AS builder
COPY . . 
RUN npm run build --configuration=production


FROM nginx:stable-alpine-slim AS production
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist/stream-client/browser  /usr/share/nginx/html