FROM node:lts-slim AS build
WORKDIR /src
RUN npm install -g @angular/cli
COPY package*.json ./
RUN npm ci
COPY . ./
RUN npx ng build --configuration=production

FROM nginx:stable AS runner
COPY --from=build src/dist/stream-client/browser  /usr/share/nginx/html