# name of the workflow
name: Build and Push Docker Image
# trigger only when code pushed in main branch
on:
  push:
    branches:
      - main
# job definition create temp linux machine ( runner )
jobs:
  build:
    runs-on: ubuntu-latest
    # steps work
    steps:
      # first checkout step : clone the repo in the runner machine
      - name: Checkout
        uses: actions/checkout@v6

      - name: Backend metadatat
        id: meta-backend
        uses: docker/metadata-action@v6
        with:
          images: ${{vars.DOCKER_USERNAME}}/streamix-backend

      - name: Frontend metadatat
        id: meta-Frontend
        uses: docker/metadata-action@v6
        with:
          images: ${{var.DOCKER_USERNAME}}/streamix-Frontend

      - name: Docker login
        uses: docker/login-action@v4
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{vars.DOCKER_PASSWORD}}

      - name: Build and Push Frontend image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend/stream-client
          tags: ${{steps.meta-Frontend.output.tags}}
