# name of the workflow
name: Build and Push Docker Image
# trigger only when code pushed in main branch
on:
  Push:
    branches:
      - main
# job definition create temp linux machine ( runner )
jobs:
  build:
    runs-on: ubuntu-latest
    # steps work
    steps:
      # first checkout step : clone the repo in the runner machine
      - name: Checkout
        uses: actions/checkout@v6
      # this step is for autmate tage and branch name and commit SHA
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.DOCKER_USERNAME }}/my-image
      # authenticate with docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{vars.DOCKER_USERNAME}}
          password: ${{vars.DOCKER_PASSWORD}}
      # build and push the image step
      - name: Build and Push Docker image
        uses: docker/build-push-action@v7
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
